name: release CI, CD workflows
on: 
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release_CI_CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
      - name: list_dir
        run: ls -la 
        
      - name: setup
        run: npm ci

      - name: show_node_modules
        run: ls node_modules
